In [1]:
import numpy as np

In [2]:
arr1=np.array([12,23,45,67,89])

In [3]:
arr1

array([12, 23, 45, 67, 89])

In [4]:
print(arr1)
print(type(arr1))
print(arr1.dtype)

[12 23 45 67 89]
<class 'numpy.ndarray'>
int32


In [5]:
arr2=np.array(['a',1,1.2])#all elements datatype will be string(U32)

In [6]:
arr2

array(['a', '1', '1.2'], dtype='<U32')

In [7]:
type(arr2[2])

numpy.str_

In [8]:
%%timeit
#arr1=np.array([12,23,45,67,89])
arr2=np.array(['a',1,1.2])

1.66 µs ± 45.2 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [9]:
arr1.shape

(5,)

In [10]:
arr1.ndim

1

In [11]:
arr1+10

array([22, 33, 55, 77, 99])

In [12]:
arr2+10

UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U32'), dtype('int32')) -> None

In [13]:
arr1[1]

23

In [14]:
#linear equation
x=np.array([23,67,34,21,89])

In [15]:
newl=x+3.4+12

In [16]:
newl

array([ 38.4,  82.4,  49.4,  36.4, 104.4])

In [17]:
y=np.arange(10)
y

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
z=np.arange(0,100,2)#even numbers between 0 and 100 
z

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [19]:
list(np.arange(1,11,1.2))#arange can have float type of step

[1.0,
 2.2,
 3.4000000000000004,
 4.6000000000000005,
 5.800000000000001,
 7.000000000000001,
 8.200000000000001,
 9.400000000000002,
 10.600000000000001]

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]]) #2d numpy array [[row1],[row2],[row3].......]

In [23]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
arr2d.ndim

2

In [25]:
arr2d.shape

(3, 3)

In [26]:
type(arr2d)

numpy.ndarray

In [27]:
arr2d.flatten() #make a 1d array 1*n

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
arr2d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [29]:
arr2d.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [51]:
arr2d.reshape(-1,3) #-1 if you dont know number of columns or  rows (if one is known and other not)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [31]:
arr2d.reshape(2,2,3) #reshape in 3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [32]:
arr2d.reshape(2,2,3).ndim

3

In [33]:
array3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [34]:
array3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [35]:
array3d.ndim

3

In [36]:
arr2d=arr2d.reshape(4,3)
arr2d

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [37]:
arr2d[1:3,1:]#slicing

array([[5, 6],
       [8, 9]])

In [38]:
arr2d[1:3,:2]#slicing

array([[4, 5],
       [7, 8]])

In [39]:
arr2d[1,1]#accessing single element

5

In [40]:
arr=np.array([2,5,4,7,2,2,8,5,-1])

In [41]:
np.unique(arr)

array([-1,  2,  4,  5,  7,  8])

In [42]:
np.mean(arr)

3.7777777777777777

In [43]:
np.max(arr)

8

In [44]:
np.abs(arr)

array([2, 5, 4, 7, 2, 2, 8, 5, 1])

In [46]:
q=np.array([1,2,3])